CREATE DATABASE PROJECT_QLSV
GO
USE PROJECT_QLSV
GO
-- DROP DATABASE PROJECT_QLSV
--DESKTOP-NHFTJ6H
-- tạo bảng cho đăng nhập 
CREATE TABLE USERS(ID CHAR(11) NOT NULL ,
					EMAIL NVARCHAR(225),
					PHONE NVARCHAR(12),
					PASSWORDS NVARCHAR(50),
					ROTE NVARCHAR(50))
-- DROP TABLE USERS
GO
ALTER TABLE USERS 
ADD CONSTRAINT PK_USERS PRIMARY KEY (ID)
-- THÊM DATA USER
GO
INSERT INTO USERS(ID,EMAIL,PHONE,PASSWORDS,ROTE)
VALUES ('23211TT1404',N'capham18@gmail.com',N'03292883674', HASHBYTES('SHA2_256', N'cp2005'),N'sinh vien'),
		 ('23211TT2984', N'user@example.com',   N'0123456789', HASHBYTES('SHA2_256', N'200225Tvg@'),N'sinh vien'),
       ('23211GV555',N'thanhthao@gmail.com',N'03465748793', HASHBYTES('SHA2_256', N'gv123456'),N'giang vien'),
		 ('bldtdc2024', N'tdc.edu.com.vn',   N'5555555', HASHBYTES('SHA2_256', N'123456tdc'),N'ban lanh dao')


-- delete  from USERS where ID = 'bldtdc2024'
-- select * from USERS
GO
ALTER TABLE USERS ADD CONSTRAINT UNI_EMAIL UNIQUE(EMAIL)
    
-- delete from USERS
-- SELECT * FROM USERS
--SELECT *
--FROM USERS
--WHERE ID = '23211TT1111'  AND PASSWORDS = HASHBYTES('SHA2_256', '200225Tvg@') AND ROTE = N'sinh vien';
 
GO          
---------------------------------------------------------------------------------------------------------------------------

CREATE TABLE TB_INSTRUCTORS(
	INSTRUCTOR_ID CHAR(20) NOT NULL,
	FULLNAME NVARCHAR(50),
	EMAIL NVARCHAR(50),
	PHONE NVARCHAR(12),
	FACULTY_ID CHAR(20) NOT NULL
)
GO
-- MÃ KHOA
CREATE TABLE TB_FACULTY (
    FACULTY_ID CHAR(20) NOT NULL,
    NAME_FY NVARCHAR(100)
)
--DROP TABLE TB_FACULATY
GO
-- CHUYÊN NGÀNH
CREATE TABLE TB_MAJOR (
    MAJOR_ID CHAR(20) NOT NULL,
    MAJOR_NAME NVARCHAR(100),
    FACULTY_ID CHAR(20) -- Kết nối đến bảng TB_DEPARTMENT
)
--DROP TABLE TB_MAJOR
GO
CREATE TABLE TB_SUBJECT(
	SUBJECT_ID CHAR(20) NOT NULL,
	NAME_ST NVARCHAR(50),
	SOTC INT NOT NULL,
	SOTIET INT NOT NULL,
	DGTC FLOAT DEFAULT 0,
	MAJOR_ID CHAR(20) NOT NULL,
	INSTRUCTOR_ID CHAR(20) NOT NULL
)

GO
-- TABLE SCORE
CREATE TABLE TB_SCORE(
	SUBJECT_ID CHAR(20) NOT NULL,
	STUDENT_ID CHAR(20) NOT NULL,
	SCORE FLOAT NOT NULL)
GO
--DROP TABLE TB_SCORE

-- TABLE TB_CLASS
CREATE TABLE TB_CLASS (
    CLASS_ID CHAR(20) NOT NULL,
	CLASS_NAME NVARCHAR(20) UNIQUE,
    FACULTY_ID CHAR(20) NOT NULL,  -- Kết nối với bảng TB_FACULTY (khoa)
    MAJOR_ID CHAR(20) NOT NULL,     -- Kết nối với bảng TB_MAJOR (ngành)	
    PRIMARY KEY (CLASS_ID)
);
GO
-- update thêm cột buổi dậy
ALTER TABLE TB_CLASS
ADD SCHEDULE NVARCHAR(10) NULL,
	TEACHING_SESSION NVARCHAR(50) NULL
GO
--ALTER TABLE TB_CLASS
--DROP COLUMN CLASS_NAME
GO
---- TABLE ĐĂNG KÝ HỌC PHẦN
CREATE TABLE TB_ENROLLMENT (
	Registration_ID CHAR(20) NOT NULL,
    STUDENT_ID CHAR(20) NOT NULL, -- Kết nối đến bảng TB_STUDENT
    SUBJECT_ID CHAR(20) NOT NULL, -- Kết nối đến bảng TB_COURSE
    ENROLLMENT_AT DATE,
)
-- DROP TABLE TB_ENROLLMENT
GO
CREATE TABLE TB_SCHEDULE (
    STUDENT_ID CHAR(20) NOT NULL, -- Kết nối đến bảng TB_COURSE
    DAY_OF_WEEK NVARCHAR(20) NOT NULL,
    START_TIME NVARCHAR(20) NOT NULL,	
    END_TIME NVARCHAR(20) NOT NULL,
    SUBJECT_ID CHAR(20) NOT NULL,
)

-- DROP TABLE TB_SCHEDULE
GO
-- BẢNG HÓA ĐƠN ĐĂNG KÝ
CREATE TABLE TB_INVOICE(
	INVOICE_ID CHAR(20) PRIMARY KEY,
	STUDENT_ID CHAR(20),
	SUBJECT_ID CHAR(20),
	DATEREGISTER DATE,
)
GO
ALTER TABLE TB_INVOICE
ADD TYPESUBJECT NVARCHAR(20)
GO
CREATE TABLE TB_VIOLATESV (
    VIOLATESV_ID CHAR(20) PRIMARY KEY, 
    VIOLATION_NAME NVARCHAR(100),
    STUDENT_ID CHAR(20),
    SUBJECT_ID CHAR(20)
)

GO
--------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE TB_TUITIONFESS (
    TUITIONFEEID_ID CHAR(20) PRIMARY KEY,        
    STUDENT_ID CHAR(20),      
    SEMESTER NVARCHAR(20) NOT NULL,               
    ACADEMICYEAR NVARCHAR(9) NOT NULL,        
    SUBJECT_ID CHAR(20),      
    CREDITUNITPRICE FLOAT NULL CHECK (CREDITUNITPRICE > 0),  
    TOTALTUITION FLOAT NULL,
    PAYMENTDATE DATE NULL,                           
    STATUSHP NVARCHAR(50) DEFAULT 'CHƯA ĐÓNG', 
    CLASS_NAME NVARCHAR(20)

--DROP TABLE TB_TUITIONFESS
);

GO
-- Tạo các bảng quản lý sinh viên
CREATE TABLE TB_STUDENTS(
	STUDENT_ID CHAR(20) NOT NULL,
	FULLNAME NVARCHAR(50),
	GENDER NVARCHAR(5),
	EMAIL NVARCHAR(225) UNIQUE NOT NULL,
	PHONE NVARCHAR(12) ,
	ADDRRES NVARCHAR(225),
	BIRTH_OF_DATE DATE,
	FACULTY_ID CHAR(20) NOT NULL,
	MAJOR_ID CHAR(20) NOT NULL,
	CLASS_NAME NVARCHAR(20) NOT NULL
)	
GO

--------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------- Thêm primary key cho các bảng -------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- TB_STUDENT
ALTER TABLE TB_STUDENTS
ADD CONSTRAINT PK_SV PRIMARY KEY(STUDENT_ID)
GO
-- TB_FACULATY
ALTER TABLE TB_FACULTY
ADD CONSTRAINT PK_MK PRIMARY KEY(FACULTY_ID)
GO
ALTER TABLE TB_MAJOR
ADD CONSTRAINT PK_MNGANH PRIMARY KEY(MAJOR_ID)
GO
ALTER TABLE TB_INSTRUCTORS
ADD CONSTRAINT PK_ITS PRIMARY KEY(INSTRUCTOR_ID)
GO
-- TB_SUBJECT
ALTER TABLE TB_SUBJECT
ADD CONSTRAINT PK_SUB PRIMARY KEY(SUBJECT_ID)
GO
-- TB_SCORE
ALTER TABLE TB_SCORE
ADD CONSTRAINT PK_SCE PRIMARY KEY(SUBJECT_ID,STUDENT_ID)
--ALTER TABLE TB_SCORE
--DROP CONSTRAINT PK_SCE
GO
-- TB_ENROLLMENT
ALTER TABLE TB_ENROLLMENT
ADD CONSTRAINT PK_ENROLLMENT PRIMARY KEY(STUDENT_ID,SUBJECT_ID,Registration_ID)
GO
-- TB_SCHEDULE
ALTER TABLE TB_SCHEDULE
ADD CONSTRAINT PK_SCHEDULE PRIMARY KEY (STUDENT_ID, DAY_OF_WEEK, START_TIME, END_TIME);
--ALTER TABLE TB_SCHEDULE
--DROP CONSTRAINT PK_SCHEDULE;
GO
--------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------ REFERENCES THAM CHIẾU TB khóa ngoại-------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------
-- KHOA THAM CHIẾU ĐẾN NGANH
ALTER TABLE TB_MAJOR
ADD CONSTRAINT FK_TC_MR FOREIGN KEY(FACULTY_ID)
REFERENCES TB_FACULTY(FACULTY_ID)
GO
-- SINH VIÊN THAM CHIẾU ĐẾN ĐIỂM
ALTER TABLE TB_SCORE
ADD CONSTRAINT FK_SE_STUDENT FOREIGN KEY(STUDENT_ID)
REFERENCES TB_STUDENTS(STUDENT_ID)

--ALTER TABLE TB_SCORE
--DROP CONSTRAINT FK_SE_STUDENT
GO
-- MÔN HỌC THAM CHIẾU ĐẾN ĐIỂM
ALTER TABLE TB_SCORE
ADD CONSTRAINT FK_SUB FOREIGN KEY(SUBJECT_ID)
REFERENCES TB_SUBJECT(SUBJECT_ID)

GO
-- DEFAULT CHO ĐIỂM
ALTER TABLE TB_SCORE ADD CONSTRAINT DFT_DIEM DEFAULT 0.0 FOR SCORE 

GO
--  MÃ KHOA THAM CHIẾU ĐẾN SINH VIÊN
ALTER TABLE TB_STUDENTS
ADD CONSTRAINT FK_SS_KHOA FOREIGN KEY(FACULTY_ID)
REFERENCES TB_FACULTY(FACULTY_ID)

--alter table TB_STUDENTS
--drop constraint FK_SS_KHOA
GO
--  MÃ NGANH THAM CHIẾU ĐẾN SINH VIÊN
ALTER TABLE TB_STUDENTS
ADD CONSTRAINT FK_SS_NGANH FOREIGN KEY(MAJOR_ID)
REFERENCES TB_MAJOR(MAJOR_ID)

--alter table TB_STUDENTS
--drop constraint FK_SS_NGANH

GO
-- check gender cho sinh viên
ALTER TABLE TB_STUDENTS ADD CONSTRAINT CK_GD CHECK (GENDER = N'NAM' OR GENDER = N'NỮ')

--alter table TB_STUDENTS
-- drop CONSTRAINT CK_GD
GO
ALTER TABLE TB_STUDENTS
ADD CONSTRAINT FK_CLASS_NAME_SV FOREIGN KEY (CLASS_NAME)
REFERENCES TB_CLASS(CLASS_NAME)

GO
-- KHOA THAM CHIẾU ĐẾN GIẢNG VIÊN
ALTER TABLE TB_INSTRUCTORS
ADD CONSTRAINT FK_TC_ITS FOREIGN KEY(FACULTY_ID)
REFERENCES TB_FACULTY(FACULTY_ID)
--ALTER TABLE TB_INSTRUCTORS
--DROP CONSTRAINT FK_TC_ITS
GO
-- GIẢNG VIÊN THAM CHIẾU ĐẾN MÔN HOC
ALTER TABLE TB_SUBJECT
ADD CONSTRAINT FK_TC_SUB FOREIGN KEY(INSTRUCTOR_ID)
REFERENCES TB_INSTRUCTORS(INSTRUCTOR_ID)
GO
--  MÃ NGÀNH THAM CHIẾU ĐẾN MÔN HOC
ALTER TABLE TB_SUBJECT
ADD CONSTRAINT FK_MH_MAGHANH FOREIGN KEY(MAJOR_ID)
REFERENCES TB_MAJOR(MAJOR_ID)
-- XÓA
--ALTER TABLE TB_SCORE
--DROP  CONSTRAINT FK_SV
GO
--  MÃ KHOA THAM CHIẾU ĐẾN LỚP
ALTER TABLE TB_CLASS
ADD CONSTRAINT FK_TC_KHOA FOREIGN KEY(FACULTY_ID)
REFERENCES TB_FACULTY(FACULTY_ID)
GO
--  MÃ NGÀNH THAM CHIẾU ĐẾN LỚP
ALTER TABLE TB_CLASS
ADD CONSTRAINT FK_CS_NGANH FOREIGN KEY(MAJOR_ID)
REFERENCES TB_MAJOR(MAJOR_ID)
GO
-- UPDATE ADD KHÓA NGOẠI
ALTER TABLE TB_CLASS
ADD SUBJECT_ID CHAR(20)
CONSTRAINT FK_CLASS_SUBJECT  FOREIGN KEY
REFERENCES TB_SUBJECT(SUBJECT_ID)  
GO
-- SINH VIÊN THAM CHIẾU ĐẾN TKB
ALTER TABLE TB_SCHEDULE
ADD CONSTRAINT FK_SDE FOREIGN KEY(STUDENT_ID)
REFERENCES TB_STUDENTS(STUDENT_ID)

--ALTER TABLE TB_SCHEDULE
--DROP CONSTRAINT FK_SDE
GO
-- MÔN HỌC THAM CHIẾU ĐẾN TKB
ALTER TABLE TB_SCHEDULE
ADD CONSTRAINT FK_SL_MH FOREIGN KEY(SUBJECT_ID)
REFERENCES TB_SUBJECT(SUBJECT_ID)
GO
-- SUBJECT_ID THAM CHIẾU ĐẾN SCHEDULE
ALTER TABLE TB_SUBJECT
ADD CONSTRAINT FK_MH_SCHEDULE FOREIGN KEY(SUBJECT_ID)
REFERENCES TB_SUBJECT(SUBJECT_ID)
GO
-- MÔN HỌC THAM CHIẾU ĐẾN ĐĂNG KÝ HỌC PHẦN
ALTER TABLE TB_ENROLLMENT
ADD CONSTRAINT FK_ENROLLMENT_M FOREIGN KEY(SUBJECT_ID)
REFERENCES TB_SUBJECT(SUBJECT_ID)
GO
--SINH VIÊN THAM CHIẾU ĐẾN ĐĂNG KÝ HỌC PHẦN
ALTER TABLE TB_ENROLLMENT
ADD CONSTRAINT FK_ENROLLMENT FOREIGN KEY(STUDENT_ID)
REFERENCES TB_STUDENTS(STUDENT_ID)
GO
ALTER TABLE TB_INVOICE
ADD CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_ID)
REFERENCES TB_STUDENTS(STUDENT_ID);
GO
ALTER TABLE TB_INVOICE
ADD CONSTRAINT FK_SUBJECT_ID FOREIGN KEY (SUBJECT_ID)
REFERENCES TB_SUBJECT(SUBJECT_ID);
GO
-- Thêm khóa ngoại cho STUDENT_ID tham chiếu đến bảng TB_STUDENTS
ALTER TABLE TB_TUITIONFESS
ADD CONSTRAINT FK_TUITIONFEES_SV FOREIGN KEY(STUDENT_ID) REFERENCES TB_STUDENTS(STUDENT_ID);
GO
-- Thêm khóa ngoại cho SUBJECT_ID tham chiếu đến bảng TB_SUBJECT
ALTER TABLE TB_TUITIONFESS
ADD CONSTRAINT FK_TUITIONFEES_MH FOREIGN KEY(SUBJECT_ID) REFERENCES TB_SUBJECT(SUBJECT_ID);
GO
-- Thêm khóa ngoại cho CLASS_NAME tham chiếu đến bảng TB_CLASS
ALTER TABLE TB_TUITIONFESS
ADD CONSTRAINT FK_TUITIONFEES_CLASS_NAME FOREIGN KEY(CLASS_NAME) REFERENCES TB_CLASS(CLASS_NAME);

GO
-- Thêm khóa ngoại cho MAJOR_ID trong TB_SUBJECT tham chiếu đến bảng TB_MAJOR
ALTER TABLE TB_SUBJECT
ADD CONSTRAINT FK_TC_MAGHANH FOREIGN KEY(MAJOR_ID) REFERENCES TB_MAJOR(MAJOR_ID);

GO
-- Thêm ràng buộc khóa ngoại cho STUDENT_ID tham chiếu đến STUDENT_ID trong bảng TB_STUDENTS
ALTER TABLE TB_VIOLATESV
ADD CONSTRAINT FK_VIOLATESV_VIOLATESV FOREIGN KEY (STUDENT_ID) REFERENCES TB_STUDENTS(STUDENT_ID);

GO
-- Thêm ràng buộc khóa ngoại cho SUBJECT_ID tham chiếu đến SUBJECT_ID trong bảng TB_SUBJECT
ALTER TABLE TB_VIOLATESV
ADD CONSTRAINT FK_SUBJECT_VIOLATESV FOREIGN KEY (SUBJECT_ID) REFERENCES TB_SUBJECT(SUBJECT_ID);

GO
-----------------------------------------------------------------------------------------------------------------
